version: '2.4'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:9200/_cluster/health']
      interval: 30s
      timeout: 10s
      retries: 4
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rg:
    image: dockerhub/sunbird-rc-core
    volumes:
      - ./config/schemas:/home/opensaber/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - elastic_search_connection_url=es:9200
      - search_provider=io.opensaber.registry.service.ElasticSearchService
      - sunbird_sso_realm=<%= props.realmName %>
      - sunbird_sso_url=http://kc:8080/auth
      - sunbird_sso_admin_client_id=<%= props.keycloakAdminClientId %>
      - sunbird_sso_client_id=<%= props.keycloakFrontendClientId %>
      - sunbird_sso_admin_client_secret=INSERT_SECRET_HERE
      - claims_url=http://cs:8082
    ports:
      - '8081:8081'
    depends_on:
      es:
        condition: service_healthy
      db:
        condition: service_started
      kc:
        condition: service_healthy
  kc:
    image: dockerhub/ndear-keycloak
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/imports
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_USER=<%= props.keycloakAdminUser %>
      - KEYCLOAK_PASSWORD=<%= props.keycloakAdminPass %>
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9990/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '8080:8080'
      - '9990:9990'
    depends_on:
      db:
        condition: service_started
  cs:
    image: dockerhub/open-saber-claim-ms
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - opensaber_url=http://rg:8081
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_started
      rg:
        condition: service_started
