apiVersion: v1
data:
  DB_PASSWORD: {{.Values.global.secrets.DB_PASSWORD | quote}}
  ELASTIC_SEARCH_PASSWORD: {{.Values.global.secrets.ELASTIC_SEARCH_PASSWORD | quote}}
  KEYCLOAK_ADMIN_CLIENT_SECRET: {{.Values.global.secrets.KEYCLOAK_ADMIN_CLIENT_SECRET | quote}}
  KEYCLOAK_ADMIN_PASSWORD: {{.Values.global.secrets.KEYCLOAK_ADMIN_PASSWORD | quote}}
  KEYCLOAK_DEFAULT_USER_PASSWORD: {{.Values.global.secrets.KEYCLOAK_DEFAULT_USER_PASSWORD | quote}}
  MINIO_SECRET_KEY: {{.Values.global.secrets.MINIO_SECRET_KEY | quote}}
kind: Secret
metadata:
  name: rc-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
