apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  labels:
    k8s-app: claims
  name: claim-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: claim-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      labels:
        k8s-app: claim-ms
    spec:
      containers:
        - env:
            - name: connectionInfo_password
              value: <db_password>
            - name: connectionInfo_uri
              value: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/claims
            - name: connectionInfo_username
              value: opensaber
            - name: opensaber_url
              value: http://registry:8081
          image: dockerhub/open-saber-claim-ms:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
#            limits:
#              cpu: 500m
          name: claim-ms
          ports:
            - containerPort: 8082
      restartPolicy: Always


