spring:
  profiles.active: default
---
spring:
  main:
    allow-bean-definition-overriding: true
  profiles: default
  servlet:
    multipart:
      enabled: true
      max-file-size: ${max_file_size:5MB}
      max-request-size: ${max_request_size:5MB}
  output:
    ansi:
      enabled: ALWAYS

name: default-yaml
environment: default

server:
  # Change this port number if you want to run it on another.
  port: ${server_port:8081}

notification:
  service:
    enabled: ${notification_enabled:false}
    connection_url: ${notification_url:http://localhost:8765/notification-service/v1/notification}
    health_url: ${notification_url:http://localhost:8765/notification-service/v1/health}
invite:
  required_validation_enabled: ${invite_required_validation_enabled:true}
  signature_enabled: ${invite_signature_enabled:true}

cors:
  # By default, allowing all domains to access this service. Choose a particular domain,
  # in production. For example, http://otherservice.com:9090, to allow requests from otherservice.com.
  allowedOrigin: ${cors_allowedOrigin:*}

perf:
  monitoring:
    enabled: ${perf_monitoring_enabled:false}

registry:
  perRequest:
    indexCreation:
      enabled: ${registry_perRequest_indexCreation_enabled:true}
  baseAPIS:
    enable: ${registry_base_apis_enable:false}
  externalentities: ${external_entities:}
  context:
    base: ${registry_context_base:http://localhost:8081/}
  system:
    base: ${registry_system_base:http://localhost:8081/sunbirdrc/}
  rootEntity:
    type: ${registry_rootentity_type:Teacher}
  schema:
    url: ${registry_schema_url:http://localhost:8081/_schemas/}
  attestationPolicy:
    createAccess: ${create_attestation_access_entities:User}
  manager:
    type: ${manager_type:DefinitionsManager}
  redis:
    host: ${redis_host:localhost}
    port: ${redis_port:6379}

workflow:
  enabled: ${workflow.enable:true}

view_template_decrypt_private_fields: ${view_template_decrypt_private_fields:false}

async:
  enabled: ${async_enabled:false}

kafka:
  bootstrapAddress: ${kafka_bootstrap_address:localhost:9092}
  createEntityTopic: ${kafka_create_entity_topic:create_entity}
  postCreateEntityTopic: ${kafka_post_create_entity_topic:post_create_entity}

webhook:
  enabled: ${webhook_enabled:false}
  url: ${webhook_url:http://localhost:5001/api/v1/callback}

conditionalAccess:
  internal: _internal
  private: _private

# This property is to be used for search request/query
# offset: search result starts from value provided as default
# limits: search result to value provided as default
search:
  offset: ${search_offset:0}
  limit: ${search_limit:2000}
  # The search mechanism to use. Values could be either NativeSearchService or ElasticSearchService
  #   If NativeSearchService, then every search API uses the same database as the writes. May
  # not offer high speed reads. This is the default search service, if this config is not provided.
  #   If ElasticSearchService, then Elastic search is used.
  expandInternal: ${search_expandInternal:true}
  removeNonPublicFieldsForNativeSearch: ${remove_non_public_fields_for_native_search:true}
  providerName: ${search_providerName:dev.sunbirdrc.registry.service.NativeSearchService}

# This property is to be used for read request
read:
  # The read mechanism to use, values could be either NativeReadService or ElasticReadService
  providerName: dev.sunbirdrc.registry.service.NativeReadService

database:
  # This property is internal and not to be confused with the schema definition.
  # Clients use this property to perform read/update operation.
  # NOTE: Once a name is chosen it must not be changed, unless you're ready to let go the
  #       existing data in the database.
  uuidPropertyName: ${database_uuidPropertyName:osid}

  # Providers available are NEO4J, SQLG, CASSANDRA, ORIENTDB, TINKERGRAPH (in-memory).
  # NOTE: Values given against 'shardId' must be unique
  provider: ${database_provider:SQLG}

  # Choose "none" as the propertyName if you don't want any shards. Otherwise
  # implement IShardAdvisor interface in your own ways. An example, SerialNumShardAdvisor
  # has been provided for reference. If you'd like to use it, set value "serialNum" here.
  # Note that "serialNum" must then be part of the payload.
  shardProperty: ${database_shardProperty:none}

  # This property is instruction to use the shard advisor.
  # Values could be dev.sunbirdrc.registry.sink.shard.DefaultShardAdvisor, OR
  # dev.sunbirdrc.registry.sink.shard.SerialNumberShardAdvisor OR
  # absolute class name of your advisor class.
  # If this property not provided, advisor is set to DefaultShardAdvisor
  shardAdvisorClassName: dev.sunbirdrc.registry.sink.shard.DefaultShardAdvisor

  connectionInfo:
    - # shardId, shardlabel must be a unique identifier to each connection.
      shardId: shard1

      # shardLabel is used as prefix for a uuid. Could be any alpha numeric string
      # Example of a record identifier: 1-60f76147-0acd-4dff-b75a-2d811787d04d
      # Note '1' is the label used for record identifier
      # shardLabel is not stored in the database
      shardLabel: 1

      # The format of the URI can be learnt from the following links -
      #     * 1. Graph database (Neo4J)
      #     ** https://github.com/SteelBridgeLabs/neo4j-gremlin-bolt
      #     ** Example : bolt://localhost:7687
      #     * 2. Relational databases (Postgresql, HSQLDB, H2, MariaDB, MySQL, MSSQLServer)
      #     ** http://sqlg.org/docs/2.0.0-SNAPSHOT/
      #     ** Example - Postgres - jdbc:postgresql://localhost:5432/yourdb
      #     * 3. NoSQL  databases (Cassandra)
      #     ** Example - cassandra - jdbc:cassandra://localhost:9160/yourdb
      uri: ${connectionInfo_uri:jdbc:postgresql://localhost:5432/registry}

      username: ${connectionInfo_username:postgres}
      password: ${connectionInfo_password:postgres}
      maxPoolSize: ${connectionInfo_maxPoolSize:200}

      # Any other shard information follows...
      #-
      #shardId: shard2
      #shardLabel: 2
      #uri: ${connectionInfo_uri:bolt://localhost:7688}
      #username: ${connectionInfo_username:neo4j}
      #password: ${connectionInfo_password:}

##################################################################################
# Uncomment the following section to use Cassandra as backend store              #
##################################################################################
cassandra:
  graphFactory: org.janusgraph.core.JanusGraphFactory
  backend: "cql"
  hostname: ${cassandra_host:localhost}
  keyspace: ${cassandra_keyspace:registry_db}
  db.cache.size: ${cassandra_db_cache_size:0.25}
  # wait time in milliseconds to clean the cache
  db.cache.clean.wait: ${cassandra_db_cache_clean_wait:60}
  index:
    storage.backend: ${cassandr_index_storage:elasticsearch}
    hostname: ${cassandra_index_hostname:localhost}

# File for framing the entity while reading
frame:
  file: ${frame_file:frame.json}

encryption:
  enabled: ${encryption_enabled:false}
  base: ${encryption_base:http://localhost:8013}
  uri: ${encryption_uri:http://localhost:8013/encrypt}
  batch:
    uri: ${encryption_batch_uri:http://localhost:8013/encrypt/obj}

decryption:
  uri: ${decryption_uri:http://localhost:8013/decrypt}
  batch:
    uri: ${decryption_batch_uri:http://localhost:8013/decrypt/obj}

signature:
  enabled: ${signature_enabled:true}
  healthCheckURL: ${sign_health_check_url:http://localhost:8079/health}
  signURL: ${sign_url:http://localhost:8079/sign}
  verifyURL: ${verify_url:http://localhost:8079/verify}
  keysURL: ${keys_url:http://localhost:8013/keys/}
  domain: ${domain_url:https://w3id.org/security/v1/}
  schema:
    config:
      name: SignatureShape

certificate:
  templateBaseUrl: ${template_base_url:http://localhost:8081/api/v1/templates/}
  healthCheckURL: ${certificate_health_check_url:http://localhost:8078/health}
  apiUrl: ${pdf_url:http://localhost:8078/api/v1/certificate}
  templateFolderPath: ${template_folder_path:public/_schemas/templates/}
  enableExternalTemplates: ${enable_external_templates:false}

# This audit configuration will enable audit logging in the system, use audit_frame.json to create a schema for database /elastic storage.
#  data_store can have following values
#   * FILE     : Store the audit log in files.
#   * DATABASE : Store the audit log in primary database configured in database properties.
#   * ELASTIC  : Store the audit log in elastic search configured in elastic properties.
#  Note : Database Stores the created audit schema in audit_schema folder.
audit:
  enabled: ${audit_enabled:true}
  frame:
    store: ${audit_frame_store:DATABASE}
    suffix: ${audit_suffix:Audit}
    suffixSeparator: ${audit_suffixSeparator:_}

keycloak:
  #publicKey:  ${sunbird_sso_publickey:pk}
  auth-server-url: ${sunbird_sso_url:https://localhost:8888/auth}
  realm: ${sunbird_sso_realm:sunbird-rc}
  resource: ${sunbird_sso_client_id:client}
keycloak-admin:
  client-id: ${sunbird_sso_admin_client_id:admin-api}
  client-secret: ${sunbird_sso_admin_client_secret:client_secret}
keycloak-user:
  set-default-password: ${sunbird_keycloak_user_set_password:false}
  default-password: ${sunbird_keycloak_user_password:abcd@123}
  # email actions which will be trigger by keycloak
  # example email actions: VERIFY_EMAIL, UPDATE_PROFILE, UPDATE_PASSWORD, TERMS_AND_CONDITIONS etc.
  # email details should be configured in keycloak realm settings
  email-actions: ${keycloack_user_email_actions:}
claims:
  url: ${claims_url:http://localhost:8081}
authentication:
  enabled: ${authentication_enabled:true}
  publicKey:  ${authentication_publickey:}
  realm:  ${authentication_realm:sunbird-rc}
  url:  ${authentication_url:localhost:8443/auth}


validation:
  enabled: ${validation_enabled:true}
  type: ${validation_type:json}

# Sets the service request and retry related configuration
service:
  connection:
    # Set the connection timeout for the underlying request configuration
    timeout: ${service_connection_timeout:5000}
    # Set the timeout in milliseconds used when requesting a connection from the connection manager using the underlying request Configuration
    request:
      timeout: ${service_connection_request_timeout:5000}
  # Set the socket read timeout for the underlying request configuration
  read:
    timeout: ${service_read_timeout:5000}
  retry:
    # The number of times an attempt must be made to reach to the service.
    maxAttempts: ${service_retry_maxAttempts:5}
    backoff:
      # The fixed time interval, in milliseconds, between each such attempt.
      delay: ${service_retry_backoff_delay:1000}

httpConnection:
  maxConnections: ${http_max_connections:100}
# Sets the task-executor configuration for threads
taskExecutor:
  index:
    # Specify the prefix to use for the names of newly created threads.
    threadPoolName: ${taskExecutor_index_threadPoolName:IndexThread-}
    # Set the ThreadPoolExecutor's core pool size.
    corePoolSize: ${taskExecutor_index_corePoolSize:2}
    # Set the ThreadPoolExecutor's maximum pool size.
    maxPoolSize: ${taskExecutor_index_maxPoolSize:2}
    # Set the capacity for the ThreadPoolExecutor's BlockingQueue.
    queueCapacity: ${taskExecutor_index_queueCapacity:100}

# Sets the task-executor configuration for threads while auditing
auditTaskExecutor:
  # Specify the prefix to use for the names of newly created threads.
  threadPoolName: ${auditTaskExecutor_threadPoolName:AuditThread-}
  # Set the ThreadPoolExecutor's core pool size.
  corePoolSize: ${auditTaskExecutor_corePoolSize:2}
  # Set the ThreadPoolExecutor's maximum pool size.
  maxPoolSize: ${auditTaskExecutor_maxPoolSize:2}
  # Set the capacity for the ThreadPoolExecutor's BlockingQueue.
  queueCapacity: ${auditTaskExecutor_queueCapacity:100}

# elastic-search configuration details
elastic:
  search:
    # elastic-search can be enable and disable through this flag
    enabled: ${elastic_search_enabled:false}
    # elastic-search connection info
    connection_url: ${elastic_search_connection_url:localhost:9200}
    add_shard_prefix: ${elastic_search_add_shard_prefix:true}
    #if authentication is enabled
    auth_enabled: ${elastic_search_auth_enabled:false}
    elastic_username: ${elastic_search_username:elastic}
    elastic_password: ${elastic_search_password:elastic}
filestorage:
  url: ${filestorage_connection_url:http://localhost:9000}
  accesskey: ${filestorage_access_key:XXXXX}
  secretkey: ${filestorage_secret_key:XXXXX}
  bucketname: ${filestorage_bucket_key:dummy}



---
##################################################################
#                      TEST PROFILE                              #
##################################################################
spring:
  main:
    allow-bean-definition-overriding: true
  profiles: test
  output:
    ansi:
      enabled: ALWAYS
name: test-yaml
enviroment: test
workflow:
  enabled: ${workflow.enable:true}

perf:
  monitoring:
    enabled: false

registry:
  context:
    base: http://example.com/voc/teacher/1.0.0/
  system:
    base: http://example.com/voc/opensaber/

# This property is to be used for read request
read:
  # The read mechanism to use, values could be either NativeReadService or ElasticReadService
  providerName: io.opensaber.registry.service.NativeReadService

database:
  # This property is internal. Clients use this property to perform read/update operation.
  # NOTE: Once a uuidPropertyName is chosen it must not be changed, unless you're ready to let go the
  #       existing data in the database.
  uuidPropertyName: ${database_uuidPropertyName:osid}

  # Providers available are NEO4J, SQLG, TINKERGRAPH, CASSANDRA, ORIENTDB.
  # NOTE: Values given against 'shardId' must be unique
  provider: ${database_provider:TINKERGRAPH}

  # Choose "none" as the propertyName if you don't want any shards. Otherwise
  # implement IShardAdvisor interface in your own ways. An example, SerialNumShardAdvisor
  # has been provided for reference. If you'd like to use it, set value "serialNum" here.
  shardProperty: ${database_shardProperty:none}

  # Any other provider breaks the unit tests, needs a work-item

# File for framing the entity while reading
frame:
  file: frame.json

encryption:
  enabled: true
  base: https://dev.sunbirded.org/encryption/
  uri: https://dev.sunbirded.org/encryption/encrypt
  batch:
    uri: https://dev.sunbirded.org/encryption/encrypt/obj

decryption:
  uri: https://dev.sunbirded.org/encryption/decrypt
  batch:
    uri: https://dev.sunbirded.org/encryption/decrypt/obj

signature:
  enabled: ${signature_enabled:true}
  healthCheckURL: ${sign_health_check_url:https://dev.sunbirded.org/encryption/}
  signURL: ${sign_url:https://dev.sunbirded.org/encryption/sign}
  verifyURL: ${verify_url:https://dev.sunbirded.org/encryption/verify}
  keysURL: ${keys_url:https://dev.sunbirded.org/encryption/keys/}
  domain: ${domain_url:https://w3id.org/security/v1/}
  schema:
    config:
      name: SignatureShape

# These properties are used to enable the audit log
# enabled : should be true to enable audit log and false to disable audit log
# store : specifies the storage option is FILE or DATABASE
# suffix : specifies the suffix given for schema. If audit schema name is Teacher_Audit.json, the suffix is Audit.
# suffixSeperator : specifies the separator used between entity name and suffix. If audit schema name is Teacher_Audit.json, the suffixSeperator is _.

audit:
  enabled: ${audit_enabled:false}
  frame:
    store: ${audit_frame_store:DATABASE}
    suffix: ${audit_suffix:Audit}
    suffixSeparator: ${audit_suffixSeparator:_}

authentication:
  enabled: ${authentication_enabled:true}
  publicKey:  ${authentication_publickey:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqe1lVD9jnQWQce62e2Q44tACqBIt5UZyGzCegxax2gddj4xotY5BDxaxuJRGKDLRpm8lPNHxX8dce8SUVAMBfk85rL+Bxv1mjspKo7Q5qsFm9TGcvE4e/4xhgpMjw6dCFt8+S87jvRjmDHjakGMooOls1kjppQiklSEZ0lW3Crqet4RNjb1FNJ+2Jg26frm8i2cpb2wRnmLDuQ9sAnHCxAD2rGxSGLXhKABptbMeTVx25eh+PVISjc78uOhAnMwOHKApVBGnVCfcUoVYqfkX8XcPQU9ybmAi27vp9xZqMfh6I56Tl4fsWYBgf8ZMl0UWyRR3PNmo/0kxon1d3zqFnwIDAQAB}
  realm:  ${authentication_realm:PartnerRegistry}
  url:  ${authentication_url:http://localhost:8443/auth/}

keycloak:
  sso:
    publicKey:  ${sunbird_sso_publickey}
    realm:  ${sunbird_sso_realm}
    auth_server_url:  ${sunbird_sso_url}

validation:
  enabled: ${validation_enabled:true}
  type: ${validation_type:json}

# Sets the service request and retry related configuration
service:
  connection:
    # Set the connection timeout for the underlying request configuration
    timeout: ${service_connection_timeout:5000}
    # Set the timeout in milliseconds used when requesting a connection from the connection manager using the underlying request Configuration
    request:
      timeout: ${service_connection_request_timeout:5000}
  # Set the socket read timeout for the underlying request configuration
  read:
    timeout: ${service_read_timeout:5000}
  retry:
    # The number of times an attempt must be made to reach to the service.
    maxAttempts: ${service_retry_maxAttempts:5}
    backoff:
      # The fixed time interval, in milliseconds, between each such attempt.
      delay: ${service_retry_backoff_delay:1000}

# Sets the task-executor configuration for threads
taskExecutor:
  index:
    # Specify the prefix to use for the names of newly created threads.
    threadPoolName: ${taskExecutor_index_threadPoolName:IndexThread-}
    # Set the ThreadPoolExecutor's core pool size.
    corePoolSize: ${taskExecutor_index_corePoolSize:2}
    # Set the ThreadPoolExecutor's maximum pool size.
    maxPoolSize: ${taskExecutor_index_maxPoolSize:2}
    # Set the capacity for the ThreadPoolExecutor's BlockingQueue.
    queueCapacity: ${taskExecutor_index_queueCapacity:3}

# Sets the task-executor configuration for threads while auditing
auditTaskExecutor:
  # Specify the prefix to use for the names of newly created threads.
  threadPoolName: ${auditTaskExecutor_threadPoolName:AuditThread-}
  # Set the ThreadPoolExecutor's core pool size.
  corePoolSize: ${auditTaskExecutor_corePoolSize:2}
  # Set the ThreadPoolExecutor's maximum pool size.
  maxPoolSize: ${auditTaskExecutor_maxPoolSize:2}
  # Set the capacity for the ThreadPoolExecutor's BlockingQueue.
  queueCapacity: ${auditTaskExecutor_queueCapacity:3}

# elastic-search configuration details
elastic:
  search:
    # elastic-search can be enable and disable through this flag
    enabled: ${elastic_search_enabled:true}
    # elastic-search connection info
    connection_url: ${elastic_search_connection_url:localhost:9200}

